services:
  sync-backend:
    image: muser-backend:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: muser-sync-backend
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=production
    networks:
      - muser-net
    ports:
      - "3000:3000"

  music-frontend:
    image: muser-frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: muser-music-frontend
    restart: unless-stopped
    networks:
      - muser-net
    ports:
      - "8084:8080"
    depends_on:
      - sync-backend

networks:
  muser-net:
    driver: bridge
